development:
  adapter: mysql2
  encoding: utf8mb4
  reconnect: false
  database: fake-orders_dev
  username: root
  password:
  host: 127.0.0.1
  port: 3306

test:
  adapter: mysql2
  encoding: utf8mb4
  reconnect: false
  database: fake-orders_test
  username: root
  password:
  host: 127.0.0.1
  port: 3306